name: day17_pipeline
version: "1.0.0"
config-version: 2
profile: day17

model-paths: ["models"]
seed-paths: []

models:
  day17_pipeline:
    staging:
      +materialized: view
    gold:
      +materialized: table

